version: "3"
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    networks:
      - flask-react-test
    volumes:
      - ./backend:/app
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - flask-react-test
    volumes:
      - ./frontend:/app
  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flask-react-test
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
networks:
    flask-react-test:
        driver: bridge
