# Pull the base image
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
ADD requirements.dev.txt ./

# Install dependencies
RUN pip install -r requirements.dev.txt

# Run internal flask server (dev only)
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
